/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.23.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.datadynamics.nifi.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DifferenceDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-13T23:19:14.614+09:00")
public class DifferenceDTO {
    @SerializedName("differenceType")
    private String differenceType = null;

    @SerializedName("difference")
    private String difference = null;

    public DifferenceDTO differenceType(String differenceType) {
        this.differenceType = differenceType;
        return this;
    }

    /**
     * The type of difference
     *
     * @return differenceType
     **/
    @ApiModelProperty(value = "The type of difference")
    public String getDifferenceType() {
        return differenceType;
    }

    public void setDifferenceType(String differenceType) {
        this.differenceType = differenceType;
    }

    public DifferenceDTO difference(String difference) {
        this.difference = difference;
        return this;
    }

    /**
     * Description of the difference
     *
     * @return difference
     **/
    @ApiModelProperty(value = "Description of the difference")
    public String getDifference() {
        return difference;
    }

    public void setDifference(String difference) {
        this.difference = difference;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DifferenceDTO differenceDTO = (DifferenceDTO) o;
        return Objects.equals(this.differenceType, differenceDTO.differenceType) &&
                Objects.equals(this.difference, differenceDTO.difference);
    }

    @Override
    public int hashCode() {
        return Objects.hash(differenceType, difference);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DifferenceDTO {\n");

        sb.append("    differenceType: ").append(toIndentedString(differenceType)).append("\n");
        sb.append("    difference: ").append(toIndentedString(difference)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

