/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.23.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.datadynamics.nifi.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.*;

/**
 * FlowRegistryClientDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-13T23:19:14.614+09:00")
public class FlowRegistryClientDTO {
    @SerializedName("id")
    private String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("uri")
    private String uri = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("bundle")
    private BundleDTO bundle = null;

    @SerializedName("properties")
    private Map<String, String> properties = null;

    @SerializedName("descriptors")
    private Map<String, PropertyDescriptorDTO> descriptors = null;

    @SerializedName("sensitiveDynamicPropertyNames")
    private List<String> sensitiveDynamicPropertyNames = null;

    @SerializedName("supportsSensitiveDynamicProperties")
    private Boolean supportsSensitiveDynamicProperties = null;

    @SerializedName("restricted")
    private Boolean restricted = null;

    @SerializedName("deprecated")
    private Boolean deprecated = null;

    @SerializedName("validationErrors")
    private List<String> validationErrors = null;
    @SerializedName("validationStatus")
    private ValidationStatusEnum validationStatus = null;
    @SerializedName("annotationData")
    private String annotationData = null;
    @SerializedName("extensionMissing")
    private Boolean extensionMissing = null;
    @SerializedName("multipleVersionsAvailable")
    private Boolean multipleVersionsAvailable = null;

    public FlowRegistryClientDTO id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The registry identifier
     *
     * @return id
     **/
    @ApiModelProperty(value = "The registry identifier")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public FlowRegistryClientDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The registry name
     *
     * @return name
     **/
    @ApiModelProperty(value = "The registry name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public FlowRegistryClientDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * The registry description
     *
     * @return description
     **/
    @ApiModelProperty(value = "The registry description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public FlowRegistryClientDTO uri(String uri) {
        this.uri = uri;
        return this;
    }

    /**
     * Get uri
     *
     * @return uri
     **/
    @ApiModelProperty(value = "")
    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public FlowRegistryClientDTO type(String type) {
        this.type = type;
        return this;
    }

    /**
     * The type of the controller service.
     *
     * @return type
     **/
    @ApiModelProperty(value = "The type of the controller service.")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public FlowRegistryClientDTO bundle(BundleDTO bundle) {
        this.bundle = bundle;
        return this;
    }

    /**
     * The details of the artifact that bundled this processor type.
     *
     * @return bundle
     **/
    @ApiModelProperty(value = "The details of the artifact that bundled this processor type.")
    public BundleDTO getBundle() {
        return bundle;
    }

    public void setBundle(BundleDTO bundle) {
        this.bundle = bundle;
    }

    public FlowRegistryClientDTO properties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    public FlowRegistryClientDTO putPropertiesItem(String key, String propertiesItem) {
        if (this.properties == null) {
            this.properties = new HashMap<String, String>();
        }
        this.properties.put(key, propertiesItem);
        return this;
    }

    /**
     * The properties of the controller service.
     *
     * @return properties
     **/
    @ApiModelProperty(value = "The properties of the controller service.")
    public Map<String, String> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, String> properties) {
        this.properties = properties;
    }

    public FlowRegistryClientDTO descriptors(Map<String, PropertyDescriptorDTO> descriptors) {
        this.descriptors = descriptors;
        return this;
    }

    public FlowRegistryClientDTO putDescriptorsItem(String key, PropertyDescriptorDTO descriptorsItem) {
        if (this.descriptors == null) {
            this.descriptors = new HashMap<String, PropertyDescriptorDTO>();
        }
        this.descriptors.put(key, descriptorsItem);
        return this;
    }

    /**
     * The descriptors for the controller service properties.
     *
     * @return descriptors
     **/
    @ApiModelProperty(value = "The descriptors for the controller service properties.")
    public Map<String, PropertyDescriptorDTO> getDescriptors() {
        return descriptors;
    }

    public void setDescriptors(Map<String, PropertyDescriptorDTO> descriptors) {
        this.descriptors = descriptors;
    }

    public FlowRegistryClientDTO sensitiveDynamicPropertyNames(List<String> sensitiveDynamicPropertyNames) {
        this.sensitiveDynamicPropertyNames = sensitiveDynamicPropertyNames;
        return this;
    }

    public FlowRegistryClientDTO addSensitiveDynamicPropertyNamesItem(String sensitiveDynamicPropertyNamesItem) {
        if (this.sensitiveDynamicPropertyNames == null) {
            this.sensitiveDynamicPropertyNames = new ArrayList<String>();
        }
        this.sensitiveDynamicPropertyNames.add(sensitiveDynamicPropertyNamesItem);
        return this;
    }

    /**
     * Set of sensitive dynamic property names
     *
     * @return sensitiveDynamicPropertyNames
     **/
    @ApiModelProperty(value = "Set of sensitive dynamic property names")
    public List<String> getSensitiveDynamicPropertyNames() {
        return sensitiveDynamicPropertyNames;
    }

    public void setSensitiveDynamicPropertyNames(List<String> sensitiveDynamicPropertyNames) {
        this.sensitiveDynamicPropertyNames = sensitiveDynamicPropertyNames;
    }

    public FlowRegistryClientDTO supportsSensitiveDynamicProperties(Boolean supportsSensitiveDynamicProperties) {
        this.supportsSensitiveDynamicProperties = supportsSensitiveDynamicProperties;
        return this;
    }

    /**
     * Whether the reporting task supports sensitive dynamic properties.
     *
     * @return supportsSensitiveDynamicProperties
     **/
    @ApiModelProperty(value = "Whether the reporting task supports sensitive dynamic properties.")
    public Boolean isSupportsSensitiveDynamicProperties() {
        return supportsSensitiveDynamicProperties;
    }

    public void setSupportsSensitiveDynamicProperties(Boolean supportsSensitiveDynamicProperties) {
        this.supportsSensitiveDynamicProperties = supportsSensitiveDynamicProperties;
    }

    public FlowRegistryClientDTO restricted(Boolean restricted) {
        this.restricted = restricted;
        return this;
    }

    /**
     * Whether the reporting task requires elevated privileges.
     *
     * @return restricted
     **/
    @ApiModelProperty(value = "Whether the reporting task requires elevated privileges.")
    public Boolean isRestricted() {
        return restricted;
    }

    public void setRestricted(Boolean restricted) {
        this.restricted = restricted;
    }

    public FlowRegistryClientDTO deprecated(Boolean deprecated) {
        this.deprecated = deprecated;
        return this;
    }

    /**
     * Whether the reporting task has been deprecated.
     *
     * @return deprecated
     **/
    @ApiModelProperty(value = "Whether the reporting task has been deprecated.")
    public Boolean isDeprecated() {
        return deprecated;
    }

    public void setDeprecated(Boolean deprecated) {
        this.deprecated = deprecated;
    }

    public FlowRegistryClientDTO validationErrors(List<String> validationErrors) {
        this.validationErrors = validationErrors;
        return this;
    }

    public FlowRegistryClientDTO addValidationErrorsItem(String validationErrorsItem) {
        if (this.validationErrors == null) {
            this.validationErrors = new ArrayList<String>();
        }
        this.validationErrors.add(validationErrorsItem);
        return this;
    }

    /**
     * Gets the validation errors from the reporting task. These validation errors represent the problems with the reporting task that must be resolved before it can be scheduled to run.
     *
     * @return validationErrors
     **/
    @ApiModelProperty(value = "Gets the validation errors from the reporting task. These validation errors represent the problems with the reporting task that must be resolved before it can be scheduled to run.")
    public List<String> getValidationErrors() {
        return validationErrors;
    }

    public void setValidationErrors(List<String> validationErrors) {
        this.validationErrors = validationErrors;
    }

    public FlowRegistryClientDTO validationStatus(ValidationStatusEnum validationStatus) {
        this.validationStatus = validationStatus;
        return this;
    }

    /**
     * Indicates whether the Processor is valid, invalid, or still in the process of validating (i.e., it is unknown whether or not the Processor is valid)
     *
     * @return validationStatus
     **/
    @ApiModelProperty(value = "Indicates whether the Processor is valid, invalid, or still in the process of validating (i.e., it is unknown whether or not the Processor is valid)")
    public ValidationStatusEnum getValidationStatus() {
        return validationStatus;
    }

    public void setValidationStatus(ValidationStatusEnum validationStatus) {
        this.validationStatus = validationStatus;
    }

    public FlowRegistryClientDTO annotationData(String annotationData) {
        this.annotationData = annotationData;
        return this;
    }

    /**
     * The annotation data for the repoting task. This is how the custom UI relays configuration to the reporting task.
     *
     * @return annotationData
     **/
    @ApiModelProperty(value = "The annotation data for the repoting task. This is how the custom UI relays configuration to the reporting task.")
    public String getAnnotationData() {
        return annotationData;
    }

    public void setAnnotationData(String annotationData) {
        this.annotationData = annotationData;
    }

    public FlowRegistryClientDTO extensionMissing(Boolean extensionMissing) {
        this.extensionMissing = extensionMissing;
        return this;
    }

    /**
     * Whether the underlying extension is missing.
     *
     * @return extensionMissing
     **/
    @ApiModelProperty(value = "Whether the underlying extension is missing.")
    public Boolean isExtensionMissing() {
        return extensionMissing;
    }

    public void setExtensionMissing(Boolean extensionMissing) {
        this.extensionMissing = extensionMissing;
    }

    public FlowRegistryClientDTO multipleVersionsAvailable(Boolean multipleVersionsAvailable) {
        this.multipleVersionsAvailable = multipleVersionsAvailable;
        return this;
    }

    /**
     * Whether the flow registry client has multiple versions available.
     *
     * @return multipleVersionsAvailable
     **/
    @ApiModelProperty(value = "Whether the flow registry client has multiple versions available.")
    public Boolean isMultipleVersionsAvailable() {
        return multipleVersionsAvailable;
    }

    public void setMultipleVersionsAvailable(Boolean multipleVersionsAvailable) {
        this.multipleVersionsAvailable = multipleVersionsAvailable;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FlowRegistryClientDTO flowRegistryClientDTO = (FlowRegistryClientDTO) o;
        return Objects.equals(this.id, flowRegistryClientDTO.id) &&
                Objects.equals(this.name, flowRegistryClientDTO.name) &&
                Objects.equals(this.description, flowRegistryClientDTO.description) &&
                Objects.equals(this.uri, flowRegistryClientDTO.uri) &&
                Objects.equals(this.type, flowRegistryClientDTO.type) &&
                Objects.equals(this.bundle, flowRegistryClientDTO.bundle) &&
                Objects.equals(this.properties, flowRegistryClientDTO.properties) &&
                Objects.equals(this.descriptors, flowRegistryClientDTO.descriptors) &&
                Objects.equals(this.sensitiveDynamicPropertyNames, flowRegistryClientDTO.sensitiveDynamicPropertyNames) &&
                Objects.equals(this.supportsSensitiveDynamicProperties, flowRegistryClientDTO.supportsSensitiveDynamicProperties) &&
                Objects.equals(this.restricted, flowRegistryClientDTO.restricted) &&
                Objects.equals(this.deprecated, flowRegistryClientDTO.deprecated) &&
                Objects.equals(this.validationErrors, flowRegistryClientDTO.validationErrors) &&
                Objects.equals(this.validationStatus, flowRegistryClientDTO.validationStatus) &&
                Objects.equals(this.annotationData, flowRegistryClientDTO.annotationData) &&
                Objects.equals(this.extensionMissing, flowRegistryClientDTO.extensionMissing) &&
                Objects.equals(this.multipleVersionsAvailable, flowRegistryClientDTO.multipleVersionsAvailable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, description, uri, type, bundle, properties, descriptors, sensitiveDynamicPropertyNames, supportsSensitiveDynamicProperties, restricted, deprecated, validationErrors, validationStatus, annotationData, extensionMissing, multipleVersionsAvailable);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FlowRegistryClientDTO {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    bundle: ").append(toIndentedString(bundle)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("    descriptors: ").append(toIndentedString(descriptors)).append("\n");
        sb.append("    sensitiveDynamicPropertyNames: ").append(toIndentedString(sensitiveDynamicPropertyNames)).append("\n");
        sb.append("    supportsSensitiveDynamicProperties: ").append(toIndentedString(supportsSensitiveDynamicProperties)).append("\n");
        sb.append("    restricted: ").append(toIndentedString(restricted)).append("\n");
        sb.append("    deprecated: ").append(toIndentedString(deprecated)).append("\n");
        sb.append("    validationErrors: ").append(toIndentedString(validationErrors)).append("\n");
        sb.append("    validationStatus: ").append(toIndentedString(validationStatus)).append("\n");
        sb.append("    annotationData: ").append(toIndentedString(annotationData)).append("\n");
        sb.append("    extensionMissing: ").append(toIndentedString(extensionMissing)).append("\n");
        sb.append("    multipleVersionsAvailable: ").append(toIndentedString(multipleVersionsAvailable)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Indicates whether the Processor is valid, invalid, or still in the process of validating (i.e., it is unknown whether or not the Processor is valid)
     */
    @JsonAdapter(ValidationStatusEnum.Adapter.class)
    public enum ValidationStatusEnum {
        VALID("VALID"),

        INVALID("INVALID"),

        VALIDATING("VALIDATING");

        private String value;

        ValidationStatusEnum(String value) {
            this.value = value;
        }

        public static ValidationStatusEnum fromValue(String text) {
            for (ValidationStatusEnum b : ValidationStatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<ValidationStatusEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ValidationStatusEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public ValidationStatusEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return ValidationStatusEnum.fromValue(String.valueOf(value));
            }
        }
    }

}

