/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.23.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.datadynamics.nifi.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ParameterProvidersEntity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-09-13T23:19:14.614+09:00")
public class ParameterProvidersEntity {
    @SerializedName("parameterProviders")
    private List<ParameterProviderEntity> parameterProviders = null;

    public ParameterProvidersEntity parameterProviders(List<ParameterProviderEntity> parameterProviders) {
        this.parameterProviders = parameterProviders;
        return this;
    }

    public ParameterProvidersEntity addParameterProvidersItem(ParameterProviderEntity parameterProvidersItem) {
        if (this.parameterProviders == null) {
            this.parameterProviders = new ArrayList<ParameterProviderEntity>();
        }
        this.parameterProviders.add(parameterProvidersItem);
        return this;
    }

    /**
     * Get parameterProviders
     *
     * @return parameterProviders
     **/
    @ApiModelProperty(value = "")
    public List<ParameterProviderEntity> getParameterProviders() {
        return parameterProviders;
    }

    public void setParameterProviders(List<ParameterProviderEntity> parameterProviders) {
        this.parameterProviders = parameterProviders;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ParameterProvidersEntity parameterProvidersEntity = (ParameterProvidersEntity) o;
        return Objects.equals(this.parameterProviders, parameterProvidersEntity.parameterProviders);
    }

    @Override
    public int hashCode() {
        return Objects.hash(parameterProviders);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ParameterProvidersEntity {\n");

        sb.append("    parameterProviders: ").append(toIndentedString(parameterProviders)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

